// flow-typed signature: 7dc6c7a153fce4865023593c3e40e1c8
// flow-typed version: <<STUB>>/node-rsa_v^1.0.7/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-rsa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-rsa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-rsa/gruntfile' {
  declare module.exports: any;
}

declare module 'node-rsa/src/encryptEngines/encryptEngines' {
  declare module.exports: any;
}

declare module 'node-rsa/src/encryptEngines/io' {
  declare module.exports: any;
}

declare module 'node-rsa/src/encryptEngines/js' {
  declare module.exports: any;
}

declare module 'node-rsa/src/encryptEngines/node12' {
  declare module.exports: any;
}

declare module 'node-rsa/src/formats/components' {
  declare module.exports: any;
}

declare module 'node-rsa/src/formats/formats' {
  declare module.exports: any;
}

declare module 'node-rsa/src/formats/pkcs1' {
  declare module.exports: any;
}

declare module 'node-rsa/src/formats/pkcs8' {
  declare module.exports: any;
}

declare module 'node-rsa/src/libs/jsbn' {
  declare module.exports: any;
}

declare module 'node-rsa/src/libs/rsa' {
  declare module.exports: any;
}

declare module 'node-rsa/src/NodeRSA' {
  declare module.exports: any;
}

declare module 'node-rsa/src/schemes/oaep' {
  declare module.exports: any;
}

declare module 'node-rsa/src/schemes/pkcs1' {
  declare module.exports: any;
}

declare module 'node-rsa/src/schemes/pss' {
  declare module.exports: any;
}

declare module 'node-rsa/src/schemes/schemes' {
  declare module.exports: any;
}

declare module 'node-rsa/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-rsa/gruntfile.js' {
  declare module.exports: $Exports<'node-rsa/gruntfile'>;
}
declare module 'node-rsa/src/encryptEngines/encryptEngines.js' {
  declare module.exports: $Exports<'node-rsa/src/encryptEngines/encryptEngines'>;
}
declare module 'node-rsa/src/encryptEngines/io.js' {
  declare module.exports: $Exports<'node-rsa/src/encryptEngines/io'>;
}
declare module 'node-rsa/src/encryptEngines/js.js' {
  declare module.exports: $Exports<'node-rsa/src/encryptEngines/js'>;
}
declare module 'node-rsa/src/encryptEngines/node12.js' {
  declare module.exports: $Exports<'node-rsa/src/encryptEngines/node12'>;
}
declare module 'node-rsa/src/formats/components.js' {
  declare module.exports: $Exports<'node-rsa/src/formats/components'>;
}
declare module 'node-rsa/src/formats/formats.js' {
  declare module.exports: $Exports<'node-rsa/src/formats/formats'>;
}
declare module 'node-rsa/src/formats/pkcs1.js' {
  declare module.exports: $Exports<'node-rsa/src/formats/pkcs1'>;
}
declare module 'node-rsa/src/formats/pkcs8.js' {
  declare module.exports: $Exports<'node-rsa/src/formats/pkcs8'>;
}
declare module 'node-rsa/src/libs/jsbn.js' {
  declare module.exports: $Exports<'node-rsa/src/libs/jsbn'>;
}
declare module 'node-rsa/src/libs/rsa.js' {
  declare module.exports: $Exports<'node-rsa/src/libs/rsa'>;
}
declare module 'node-rsa/src/NodeRSA.js' {
  declare module.exports: $Exports<'node-rsa/src/NodeRSA'>;
}
declare module 'node-rsa/src/schemes/oaep.js' {
  declare module.exports: $Exports<'node-rsa/src/schemes/oaep'>;
}
declare module 'node-rsa/src/schemes/pkcs1.js' {
  declare module.exports: $Exports<'node-rsa/src/schemes/pkcs1'>;
}
declare module 'node-rsa/src/schemes/pss.js' {
  declare module.exports: $Exports<'node-rsa/src/schemes/pss'>;
}
declare module 'node-rsa/src/schemes/schemes.js' {
  declare module.exports: $Exports<'node-rsa/src/schemes/schemes'>;
}
declare module 'node-rsa/src/utils.js' {
  declare module.exports: $Exports<'node-rsa/src/utils'>;
}
