version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test
      - run: yarn test:typescript
workflows:
  build-and-test:
    jobs:
      - build-and-test
